export const games = [
  {
    id: "minesweeper",
    title: "踩地雷",
    icon: "💣",
    description: "清空安全區域、標出所有地雷。經典又俐落的一局。",
    category: "益智",
    duration: "3–8 分鐘",
    status: "available",
  },
  {
    id: "snake",
    title: "貪吃蛇",
    icon: "🐍",
    description: "在越來越緊湊的空間裡，挑戰自己的反應與最高分。",
    category: "街機",
    duration: "2–5 分鐘",
    status: "coming-soon",
  },
  {
    id: "reversi",
    title: "黑白棋 AI",
    icon: "◉",
    description: "規則簡單、局勢多變。用幾分鐘和 AI 較量一局。",
    category: "棋類",
    duration: "5–10 分鐘",
    status: "coming-soon",
  },
  {
    id: "solitaire",
    title: "接龍",
    icon: "🂡",
    description: "最熟悉的辦公室休閒夥伴，慢慢整理出完美牌序。",
    category: "紙牌",
    duration: "5–15 分鐘",
    status: "coming-soon",
  },
  {
    id: "tetris",
    title: "方塊挑戰",
    icon: "▦",
    description: "排列、消除、加速，在畫面填滿前刷新最佳紀錄。",
    category: "街機",
    duration: "3–10 分鐘",
    status: "coming-soon",
  },
  {
    id: "go",
    title: "9×9 圍棋 AI",
    icon: "●",
    description: "小棋盤也有大局面，適合午休時來一場短對局。",
    category: "棋類",
    duration: "8–15 分鐘",
    status: "coming-soon",
  },
];
