export const games = [
  {
    id: "minesweeper",
    title: "踩地雷",
    subtitle: "薔薇戰線的秘密",
    character: "奧蕾莉亞・羅瑟",
    role: "薔薇王國近衛軍官",
    quote: "「真正的勇氣，是在未知中仍優雅前行。」",
    portrait: 0,
    description: "跟隨公主軍官奧蕾莉亞，解開宮廷花園下埋藏的危險。",
    category: "益智",
    duration: "3–8 分鐘",
    status: "available",
  },
  {
    id: "snake",
    title: "貪吃蛇",
    subtitle: "月蝕之蛇",
    character: "西爾維斯・諾克斯",
    role: "永夜古堡的吸血鬼伯爵",
    quote: "「別害怕，黑夜只是在邀請你共舞。」",
    portrait: 1,
    description: "穿梭月夜迴廊，替神祕的吸血鬼伯爵收集失落靈魂。",
    category: "街機",
    duration: "2–5 分鐘",
    status: "coming-soon",
  },
  {
    id: "reversi",
    title: "黑白棋 AI",
    subtitle: "純白與漆黑的茶會",
    character: "諾瓦・布蘭雪",
    role: "黑白棋沙龍的首席策士",
    quote: "「勝負在落子以前，就已藏在你的眼神裡。」",
    portrait: 2,
    description: "接受天才策士諾瓦的邀請，在黑與白的茶會中與 AI 對弈。",
    category: "棋類",
    duration: "5–10 分鐘",
    status: "available",
  },
  {
    id: "solitaire",
    title: "接龍",
    subtitle: "王子的魔術牌局",
    character: "路西安・德・凡爾賽",
    role: "星輝宮廷的魔術王子",
    quote: "「命運是一副牌，而優雅的人自己決定玩法。」",
    portrait: 3,
    description: "整理王子的魔法牌組，讓錯置的命運重新回到正軌。",
    category: "紙牌",
    duration: "5–15 分鐘",
    status: "coming-soon",
  },
  {
    id: "tetris",
    title: "方塊挑戰",
    subtitle: "緋紅機巧工房",
    character: "薇奧拉・齒輪心",
    role: "皇家機巧院的天才發明家",
    quote: "「世界再混亂，也一定存在最漂亮的排列方式！」",
    portrait: 4,
    description: "協助發明家薇奧拉排列魔晶，在工房失控以前完成實驗。",
    category: "街機",
    duration: "3–10 分鐘",
    status: "coming-soon",
  },
  {
    id: "go",
    title: "9×9 圍棋 AI",
    subtitle: "月下棋譜",
    character: "沈月衡",
    role: "隱居竹庭的弈棋公子",
    quote: "「棋盤方寸之間，足以容下整片星空。」",
    portrait: 5,
    description: "在月下竹庭與月衡公子對局，於十九路星河之外尋找勝機。",
    category: "棋類",
    duration: "8–15 分鐘",
    status: "coming-soon",
  },
];
